//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_ControllerInput_example : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean in_triggerButton
        {
            get
            {
                return SteamVR_Actions.controllerInput_example_in_triggerButton;
            }
        }
        
        public virtual SteamVR_Action_Boolean gripButton
        {
            get
            {
                return SteamVR_Actions.controllerInput_example_gripButton;
            }
        }
        
        public virtual SteamVR_Action_Boolean primaryButton
        {
            get
            {
                return SteamVR_Actions.controllerInput_example_primaryButton;
            }
        }
        
        public virtual SteamVR_Action_Vector3 devicePosition
        {
            get
            {
                return SteamVR_Actions.controllerInput_example_devicePosition;
            }
        }
        
        public virtual SteamVR_Action_Boolean NewAction
        {
            get
            {
                return SteamVR_Actions.controllerInput_example_NewAction;
            }
        }
        
        public virtual SteamVR_Action_Vibration out_triggerButton
        {
            get
            {
                return SteamVR_Actions.controllerInput_example_out_triggerButton;
            }
        }
    }
}
